name: Testar Container 
on:
    workflow_dispatch:
jobs:
    build-test:
        runs-on: ubuntu-latest
        container:
            image: python:3.10.14-alpine3.20
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Verifica a versão do Python
                run: python3 --version
            -   name: Instalação curl Alpine
                run: apk add curl
            -   name: Executando o curl
                run: curl https://www.google.com
            -   name: Execução do runner
                run: cat /etc/os-release
            -   name: Execução do container
                uses: docker://alpine:latest
                with:
                    entryppint: cat
                    args: /etc/os-realese